
export const VOCDONI_CENSUS_OFFCHAIN = 'offchain'

export const VOCDONI_CENSUS_CSP_NBNS = 'csp-non-blinded-non-salted'

export const VOCDONI_CENSUS_CSP_BLINDNS = 'csp-blinded-non-salted'

export const VOCDONI_SUPPORTED_CENSUSES = [VOCDONI_CENSUS_OFFCHAIN, VOCDONI_CENSUS_CSP_NBNS, VOCDONI_CENSUS_CSP_BLINDNS]

export const VOCDONI_CSP_CENSUSES = [VOCDONI_CENSUS_CSP_NBNS, VOCDONI_CENSUS_CSP_BLINDNS]
