import { VOCDONI_CENSUS_CSP_BLINDNS, VOCDONI_CENSUS_CSP_NBNS, VOCDONI_CENSUS_OFFCHAIN } from '../vocdoni/consts'

export const PROOFSPACE_STRATEGY = 'proofspace'

export const proofspaceAllowedCensus = [VOCDONI_CENSUS_OFFCHAIN, VOCDONI_CENSUS_CSP_NBNS, VOCDONI_CENSUS_CSP_BLINDNS]
